services:
  - type: web
    name: 4th-down-decision-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
